### ISSUE TITLE
hazifeladat letoltes

### ISSUE THREAD

**Issue by zoltansx** [szekelymilan/e-kreta-cli#1]
Szia,

Nem lehetne belefejleszteni a hazifeladatok letolteset? Nagy segitseg lenne. Ha igen, akkor a legjobb lenne minden HF kulon file-ban, tanar_neve_timestamp filenevvel.

**Comment by szekelymilan** [comment]
Szia!
Köszönöm a javaslatot, el fogom kezdeni a funkció implementálását. 😃

**Comment by zoltansx** [comment]
Hát ez gyors volt, köszi ☺ 
Úgy láttam, hogy a házifeladatok html snippetek.
Ha így van, azt szerintem már nem kell konvertálni, Safari simán megnyitja, és onnan be tudom másolni a szöveget. (Kerüljük a scope creepet!)

**Comment by szekelymilan** [comment]
Átdolgoztam kicsit az eddigi kódot - a redundancia elkerülése végett -, frissítettem a dependencyket és megoldottam a házi feladatok letöltésének lehetőségét. 6f987091e883c30a36345724dd1e3a4d62a26ee4
Tantárgyanként szétbontva, időpontokkal együtt HTML-ként tölti le őket - a file elején kommentben megtalálható még pár plusz információ is.
Csekkold le a legújabb releaset! 😉

**Comment by zoltansx** [comment]
Műxik, köszi!
Extra kudos a html file-okért: konkrétan az egyik tanár meg próbált bemásolni egy képet a assignments üzenetbe, és oda <img src="data:image/png;base64,...."> ként került be, és ez a megoldás megjelenítette a képet, ahogy azt kell :)

**Comment by szekelymilan** [comment]
Remek, örülök, hogy működik. 😃
Azonban az egyik barátom nemrég jelezte, hogy a házi feladathoz lehet **tetszőleges fájlokat is csatolni** - ezt viszont már nem hiszem, hogy a jelenlegi formájában kezelné a CLI.
Én még nem kaptam ilyen házi feladatot, **amint lesz hozzáférésem** egy olyan fiókhoz, mely rendelkezik ilyen házi feladattal, ezt a **funkciót is implementálom**.
