### ISSUE TITLE
Csatolmány a házi feladatoknál

### ISSUE THREAD

**Issue by szekelymilan** [szekelymilan/e-kreta-cli#3]
A CLI valószínűleg **nem kezeli a házi feladatokhoz mellékelt csatolmányokat**, a jövőben ezt implementálni kell.
(További részletek: #1)

**Comment by FireMax12** [comment]
Támogatom, hasznosnak hangzik ;)

**Comment by szekelymilan** [comment]
Csatolmány hozzáadása **csakis üzenethez** lehetséges, házi feladathoz nem. Implementáltam egy **üzenetletöltő funkciót**, amely a **csatolmányok letöltésére** is képes. https://github.com/szekelymilan/e-kreta-cli/commit/5c568cd618d20f95eec312523555f972d04faec7
