### ISSUE TITLE
letöltés korlátozása az új feladatokra

### ISSUE THREAD

**Issue by zoltansx** [szekelymilan/e-kreta-cli#4]
Meg lehetne oldani, hogy megadott flag esetén csak az új feladatokat töltse le a kliens?
Akár úgy, hogy egy flag esetén nézni, hogy létezik-e a fájl, vagy úgy, ha az aktuális dátumhoz képest megadott offsetnél újabb feladatokat töltse le.

Fontos, hogy az összes feladatot is le lehessen tölteni, de a kréta rosszul viseli a terhelést, és a napi rutinban egyszerűbb, ha csak az újakat próbálom megszerezni.

**Comment by zoltansx** [comment]
BTW a messages rész (v0.0.4) rendben műxik 😄

**Comment by szekelymilan** [comment]
A legkézenfekvőbb megoldás szerintem, ha az **e-kreta-cli.json** fileban egy **dictionaryben tároljuk** a már letöltött házi feladatokat (`dictionary[haziID] = true`). Alapból csak **azon házi feladatokat** töltené le a CLI, amelyek **nem szerepelnek a dictionaryben**, a `--downloadAll` flag esetén pedig az összeset.

**Comment by zoltansx** [comment]
Ok, jól hangzik. (Bár nem egyszerűbb ellenőrizni, hogy a generált néven létezik-e már file?)

**Comment by szekelymilan** [comment]
Úgy nem lehetne egy **külön mappába csak az új** házi feladatokat letölteni.

**Comment by zoltansx** [comment]
Most már látom, mi a gond: van a lesson, meg az assignment, és a lessonban nem ugyanaz a tantárgy neve. (meg lehetne több assignment is .. )
Sokkal egyszerűbb lett volna, ha a lessonnal meg jött volna az assignment info, de minek az ...

**Comment by szekelymilan** [comment]
Mostantól kiválasztható a **letöltendő időintervallum**, ezáltal **korlátozható a letöltés** az új feladatokra.
