### ISSUE TITLE
Insitute search nem megy a reconfigureben

### ISSUE THREAD

**Issue by Daaniiieel** [szekelymilan/e-kreta-cli#7]
TypeError: Cannot read property 'trim' of undefined. - et dob vissza. Ha keresni akarok

**Comment by szekelymilan** [comment]
Megoldottam a problémát. A v0.0.5 verzió (accc5466024ba19dd5a33b348d15a8a71935d9cf) kiadásakor **frissítettem a dependencyket**, azonban a keresést biztosító dependency **használata megváltozott** - emiatt dobott hibát.
Köszi, hogy jelezted. 😃
